Train:
  Base:
    use_cuda: True
    basedir: './logs'
    expname: 'lego_v8'
    seed: 0
    lrate: 5e-4
    lrate_decay: 500
    max_train_views: 8
    chunk: 32768                              # 1024*32
    pixel_interp_mode: 'bicubic'
    # Consistency loss options
    consistency_loss: False
    # Rendering
    render_autocast: False
    render_loss_interval: 1
    render_nH: 32
    render_nW: 32
    render_jitter_rays: False
    precrop_iters: 500
    precrop_frac: 0.5
    #Visualize
    wandb: True
    N_iters: 200000
    print_iters: 50
    save_iters: 10000
    video_iters: 6250                         # 50000 100v
    testset_iters: 50000
    log_iters: 1   
    log_raw_hist_iters: 50                     # 2 100v
    img_iters: 500

  Dataset:
    dataset_type: 'blender'
    datadir: '../example/nerf_synthetic/lego'
    factor: 8
    spherify: False
    llffhold: 8
    no_ndc: False                            # do not use normalized device coordinates (set for non-forward facing scenes)
    half_res: True
    testskip: 8
    num_render_poses: 40
    white_bkgd: True
  
  Model:
    load_weight: True 
    multires: 10
    multires_views: 4
    i_embed: 0
    netchunk_per_gpu: 262144                 # 1024*64*4
    N_samples: 64
    perturb: 1.0
    raw_noise_std: 0.0
    N_rand: 1024
    use_softplus_alpha: False
    checkpoint_rendering: False
    lindisp: False
    # coarase
    netdepth: 8
    netwidth: 256
    # fine 
    use_viewdirs: True
    N_importance: 128
    netdepth_fine: 8
    netwidth_fine: 256
  
  Custom:
    rel_depth_path: './llff_rel_depths/'
    num_total_views: 20